const fs = require("fs");
const path = require("path");

const sourceDoc =
  "data/season-two-exemplars/FINAL-PD-Script Generator Refinement Project June 7-13.docx";

const outroFull = [
  "❤️ Proverbs Daily",
  "Is a reader and listener-supported program.",
  "Every post is free —",
  "but if you'd like to help spread the message",
  "and make the sacred positively contagious,",
  "tap Subscribe or Upgrade and join us.",
  "Thank you in advance for your support!",
  "",
  "👋🏽 About the Author",
  "Fred Lynch — creative communicator, author & Christian hip-hop pioneer.",
  "To connect everywhere hit me at: @heyfredlynch on all the socials and we’ll connect.",
  "Want daily wisdom on your phone?",
  "Go to ProverbsDaily.org",
  "Thanks again and please Like + Share to help someone walk in wisdom.",
  "Be wise. Be well.",
  "Peace.",
].join("\n");

const episodes = [
  {
    date: "2026-06-07",
    day: "Sunday",
    dayLine: "Sunday June 7",
    reference: "Proverbs 7:1",
    spokenReference: "Proverbs chapter seven, verse one",
    translation: "ESV",
    filename: "2026-06-07-proverbs-7-1",
    title: "How Treasures Are Measured",
    verse:
      "“My son, keep my words and treasure up my commandments with you.”",
    devotional: [
      "Some treasures are priceless.",
      "",
      "Not because they’re expensive.",
      "",
      "Because they’re personal.",
      "",
      "A child may treasure a worn-out stuffed animal.",
      "",
      "A grandmother may treasure a faded photograph.",
      "",
      "A husband may treasure a wedding ring.",
      "",
      "To everyone else, those things might seem ordinary.",
      "",
      "But pricelessness isn’t determined by the market.",
      "",
      "It’s determined by the meaning.",
      "",
      "And meaning comes from relationship.",
      "",
      "Notice the language.",
      "",
      "God doesn’t just say:",
      "",
      "“Remember my commandments.”",
      "",
      "He says:",
      "",
      "“Treasure them.”",
      "",
      "Store them up.",
      "",
      "Keep them close.",
      "",
      "Protect them.",
      "",
      "Value them.",
      "",
      "Why?",
      "",
      "Because treasures are never measured by what they cost.",
      "",
      "They’re measured by what they’re worth to the one holding them.",
      "",
      "Beauty is in the eye of the beholder.",
      "",
      "And treasure is measured the same way.",
      "",
      "The value isn’t merely in the object.",
      "",
      "The value is in the relationship.",
      "",
      "That’s why one person can read Scripture and see ink on paper.",
      "",
      "While another person reads the same words and finds life.",
      "",
      "One sees information.",
      "",
      "The other sees treasure.",
      "",
      "Think about your phone.",
      "",
      "Most of the pictures on it wouldn’t mean much to a stranger.",
      "",
      "But to you?",
      "",
      "That’s your child. That’s your spouse. That’s your family. That’s a memory you’ll never get back.",
      "",
      "The value isn’t in the pixels.",
      "",
      "The value is in the relationship.",
      "",
      "The same is true with God’s Word.",
      "",
      "The more you walk with Him, the more valuable His words become.",
      "",
      "Not because the words changed.",
      "",
      "Because the relationship deepened.",
      "",
      "Maybe that’s why some Scriptures have carried you for years.",
      "",
      "A verse that once seemed ordinary became precious.",
      "",
      "A promise you once overlooked became a lifeline.",
      "",
      "Over time, God’s Word stopped being something you read.",
      "",
      "It became something you treasured.",
      "",
      "And that’s a beautiful sign of spiritual maturity.",
      "",
      "Because mature faith doesn’t merely collect verses.",
      "",
      "It cherishes them.",
    ],
    remember:
      "Treasures are measured by the relationship, not the price tag.",
    prayer: "God, teach me to treasure Your words above all else.",
    challenge: [
      "Identify one Scripture that has become precious to you.",
      "",
      "Write it down.",
      "",
      "Carry it with you today.",
      "",
      "And ask yourself:",
      "",
      "“What makes this verse so valuable to me?”",
      "",
      "The answer may reveal something beautiful about your relationship with God.",
    ],
    visual: {
      opening: "Start close and personal: Fred holding a small everyday object that clearly matters to him, then pivoting to the idea of relational value.",
      typography: "Animate the words “keep,” “treasure,” and “with you” as if being placed into a keepsake box.",
      broll: "Hands scrolling family photos, a wedding ring, an old photograph, a marked-up Bible, a Scripture card tucked into a pocket.",
      onscreen: ["Some treasures are personal.", "Treasure is measured by relationship.", "One sees information. The other sees treasure."],
      tone: "Warm, reflective, grateful, intimate.",
      pacing: "Gentle open, spacious middle, warm lift into the challenge.",
      background: "Soft home-office or desk setting with Bible, journal, and a personal keepsake in frame.",
      clips: ["Why one verse can become priceless", "Information vs. treasure", "The Scripture you carry with you"],
      thumb: "How Treasures Are Measured - Proverbs 7:1",
      cues: "Let the pauses after “Because they’re personal” and “Because the relationship deepened” breathe.",
    },
  },
  {
    date: "2026-06-08",
    day: "Monday",
    dayLine: "Monday June 8",
    reference: "Proverbs 8:3",
    spokenReference: "Proverbs chapter eight, verse three",
    translation: "NLT",
    filename: "2026-06-08-proverbs-8-3",
    title: "Location, Location, Location",
    verse:
      "“By the gates at the entrance to the town, on the road leading in, she cries aloud.”",
    devotional: [
      "If you’ve ever talked to someone in real estate, you’ve probably heard the phrase:",
      "",
      "“Location, location, location.”",
      "",
      "Why?",
      "",
      "Because if you want people to find you, your business, your product, or your service, you’ve got to be in the right place.",
      "",
      "Success often comes down to placement.",
      "",
      "And when it comes to wisdom…",
      "",
      "Talk about product placement!",
      "",
      "Wisdom was with God when He created the world. She understands something about positioning. So if you’re looking for a bit of wisdom to help you out in your journey today, take a look at her résumé and she’ll tell you right where she’s at located:",
      "",
      "Did you catch that? Wisdom says she’s everywhere!",
      "",
      "At the gates.",
      "",
      "At the entrance.",
      "",
      "At the crossroads.",
      "",
      "At the places where people are coming and going.",
      "",
      "At the places where decisions are being made.",
      "",
      "I like to think of it like this right when you are at the precipice of a decision… At the brink of execution of an idea… Look up because",
      "",
      "She (wisdom) already there anticipating your arrival and willing to partner with you in your next move.",
      "",
      "Waiting.",
      "",
      "Speaking.",
      "",
      "Calling.",
      "",
      "In other words, wisdom understands location.",
      "",
      "She positions herself wherever life is happening.",
      "",
      "Where choices are being made.",
      "",
      "Where futures are being shaped.",
      "",
      "Where people need direction.",
      "",
      "If you’ve ever raised children, you know this feeling.",
      "",
      "You tell them something for years.",
      "",
      "Years.",
      "",
      "Then one day a coach, a teacher, a friend, or a complete stranger says the exact same thing.",
      "",
      "Suddenly your child looks at them like they’re a genius.",
      "",
      "And you’re standing there thinking:",
      "",
      "“I’ve been saying that the whole time!”",
      "",
      "Wisdom understands that feeling.",
      "",
      "Humanity has ignored her for centuries.",
      "",
      "Yet every morning she shows up again.",
      "",
      "At the gate.",
      "",
      "At the crossroads.",
      "",
      "At the entrance.",
      "",
      "Still speaking.",
      "",
      "Still available.",
      "",
      "Still present.",
      "",
      "Maybe today you’re discouraged because you fell that people aren’t listening.",
      "",
      "Maybe you’ve been faithful.",
      "",
      "Showing up.",
      "",
      "Serving.",
      "",
      "Teaching.",
      "",
      "Loving.",
      "",
      "Repeating the same life-giving truth over and over.",
      "",
      "Don’t quit your post.",
      "",
      "Wisdom doesn’t.",
      "",
      "She stays in place because she knows that eventually someone will hear.",
      "",
      "And when they do, it can change everything.",
    ],
    remember:
      "Wisdom’s power isn’t just in what she says.\nIt’s in where she stays.",
    prayer: "God, help me stay faithful where You’ve strategically placed me.",
    challenge: [
      "Identify one place God has positioned you to influence others.",
      "",
      "A workplace.",
      "",
      "A family.",
      "",
      "A friendship.",
      "",
      "A ministry.",
      "",
      "Instead of wishing for another location, be fully present and embody the assignment of that location today.",
    ],
    visual: {
      opening: "Open with Fred using the real-estate phrase, then snap the idea toward wisdom being positioned at decision points.",
      typography: "Map-style words appear: GATES, ENTRANCE, CROSSROADS, DECISIONS.",
      broll: "City crosswalks, open gates, workplace entrance, school drop-off, kitchen table conversation, parent watching a coach talk to a child.",
      onscreen: ["Location, location, location.", "Wisdom shows up where life happens.", "Don’t quit your post."],
      tone: "Encouraging, slightly humorous, steady.",
      pacing: "Quick hook, energetic middle, pastoral encouragement in the final third.",
      background: "Urban doorway or street-corner visual language; keep it bright and accessible.",
      clips: ["Wisdom understands location", "Don’t quit your post", "When someone finally hears"],
      thumb: "Location, Location, Location - Proverbs 8:3",
      cues: "Lean into the humor of “I’ve been saying that the whole time!” without losing the encouragement.",
    },
  },
  {
    date: "2026-06-09",
    day: "Tuesday",
    dayLine: "Tuesday June 9",
    reference: "Proverbs 9:14",
    spokenReference: "Proverbs chapter nine, verse fourteen",
    translation: "TPT",
    filename: "2026-06-09-proverbs-9-14",
    title: "Watch Who’s Whispering",
    verse:
      "“And there she sits at the gateway to the high places, on her throne overlooking the city.”",
    extractionNote:
      "The FINAL docx merged the verse text and episode-title heading in one paragraph; content was separated according to the visible source text.",
    devotional: [
      "Do you remember the infamous slap seen around the world?",
      "",
      "The 2022 Academy Awards.",
      "",
      "Will Smith walks on stage and slaps Chris Rock in front of millions of viewers.",
      "",
      "Now here’s what’s fascinating.",
      "",
      "Will Smith wasn’t some unknown person struggling to make it.",
      "",
      "He was at the top.",
      "",
      "Successful. Respected. Award-winning.",
      "",
      "In fact, he was only moments away from receiving one of the highest honors of his career.",
      "",
      "Yet in a single moment, one thought, one impulse, one decision changed the entire conversation.",
      "",
      "How does that happen?",
      "",
      "How can someone who has accomplished so much suddenly do something so foolish?",
      "",
      "Proverbs gives us an answer:",
      "",
      "This verse is talking about Folly.",
      "",
      "The foolish voice.",
      "",
      "The destructive voice.",
      "",
      "And notice where she is sitting.",
      "",
      "At the gateway.",
      "",
      "In the high places.",
      "",
      "Overlooking the city.",
      "",
      "In other words, Folly isn’t hiding in some dark alley.",
      "",
      "She’s positioned right where people enter.",
      "",
      "Right where decisions are made.",
      "",
      "Right where influence is gained.",
      "",
      "Just like Wisdom stands at the crossroads calling out to us, Folly sits nearby offering her own suggestions.",
      "",
      "Her timing is strategic.",
      "",
      "She doesn’t wait until you’re at your worst.",
      "",
      "She often shows up when you’re at your best.",
      "",
      "When you’re successful. When you’re celebrated. When you’re finally getting what you’ve worked for.",
      "",
      "That’s when she leans in and whispers.",
      "",
      "Human beings have an incredible capacity for good.",
      "",
      "We create art. Build families. Care for others. Change lives.",
      "",
      "But we also have the capacity to make spectacularly bad decisions.",
      "",
      "Not because we’re evil.",
      "",
      "Because we listen to the wrong voice.",
      "",
      "One foolish thought can feel reasonable in the moment.",
      "",
      "One impulsive reaction can seem justified.",
      "",
      "One emotional response can masquerade as wisdom.",
      "",
      "That’s why Proverbs warns us to pay attention to who’s talking inside our heads.",
      "",
      "After the Oscars incident, Denzel Washington shared something with Will Smith that has been repeated many times since.",
      "",
      "He said:",
      "",
      "“At your highest moment, be careful. That’s when the devil comes for you.”",
      "",
      "Whether you agree with every detail of that statement or not, the principle is powerful.",
      "",
      "When you’re on top, don’t assume you’re immune.",
      "",
      "When you’re winning, don’t assume every thought deserves your trust.",
      "",
      "When you’re emotional, don’t assume every impulse deserves your obedience.",
      "",
      "The good news is that wisdom is speaking too.",
      "",
      "You don’t have to follow every voice that enters your mind.",
      "",
      "You can pause.",
      "",
      "You can examine it.",
      "",
      "You can choose differently.",
    ],
    remember: "Not every thought deserves your trust.",
    prayer: "God, help me recognize wisdom’s voice above every foolish whisper.",
    challenge: [
      "The next time a strong thought enters your mind today, say it out loud before acting on it.",
      "",
      "Hearing it may give you the extra second needed to examine it.",
      "",
      "Ask yourself:",
      "",
      "Is this wisdom speaking?",
      "",
      "Or is this folly whispering?",
    ],
    visual: {
      opening: "Open talking-head with the cultural memory of the 2022 Academy Awards, then move quickly from spectacle to self-examination.",
      typography: "Dark-light split typography: WISDOM SPEAKING / FOLLY WHISPERING.",
      broll: "Award-show lights in abstract, city overlook, throne/gateway imagery, close-up of someone pausing before reacting.",
      onscreen: ["At your highest moment, be careful.", "Not every thought deserves your trust.", "Pause. Examine. Choose."],
      tone: "Serious, discerning, cautionary but hopeful.",
      pacing: "Measured and dramatic early, then slow down around the Denzel quote and the closing choices.",
      background: "Subtle high-place/city-overlook motif, with restrained contrast.",
      clips: ["Not every thought deserves trust", "Folly shows up when you’re winning", "Pause before you obey the impulse"],
      thumb: "Watch Who’s Whispering - Proverbs 9:14",
      cues: "Lower the voice slightly on “That’s when she leans in and whispers.”",
    },
  },
  {
    date: "2026-06-10",
    day: "Wednesday",
    dayLine: "Wednesday June 10",
    reference: "Proverbs 10:3",
    spokenReference: "Proverbs chapter ten, verse three",
    translation: "ESV",
    filename: "2026-06-10-proverbs-10-3",
    title: "God Be Meddling",
    verse:
      "“The Lord does not let the righteous go hungry, but he thwarts the craving of the wicked.”",
    extractionNote:
      "The FINAL docx merged the revisited verse and scripture-breakdown heading in one paragraph; content was separated according to the visible source text.",
    devotional: [
      "Have you ever had something not work out and later realized it was one of the best things that could have happened?",
      "",
      "The relationship ended.",
      "",
      "The deal fell through.",
      "",
      "The opportunity disappeared.",
      "",
      "The door slammed shut.",
      "",
      "And at the time all you could think was:",
      "",
      "“Why, God?”",
      "",
      "Then years later you look back and say:",
      "",
      "“Thank God.”",
      "",
      "Funny how that works.",
      "",
      "Sometimes what feels like rejection turns out to be protection.",
      "",
      "Sometimes what feels like disappointment turns out to be direction.",
      "",
      "Or as we might say where I come from:",
      "",
      "God be meddling.",
      "",
      "The word that catches my attention is “thwarts.”",
      "",
      "Some translations say frustrates.",
      "",
      "Others say rejects.",
      "",
      "Either way, God is interfering with something.",
      "",
      "But notice carefully what He opposes.",
      "",
      "The proverb doesn’t say God frustrates the person.",
      "",
      "It says He frustrates the craving.",
      "",
      "The appetite.",
      "",
      "The desire.",
      "",
      "The impulse.",
      "",
      "And that’s an important distinction.",
      "",
      "Because God isn’t out to get people.",
      "",
      "He’s out to get people free.",
      "",
      "Sometimes the thing standing between us and freedom is the very thing we want most.",
      "",
      "Think about a small child reaching for an electrical outlet.",
      "",
      "The child sees curiosity.",
      "",
      "The parent sees danger.",
      "",
      "The child experiences frustration.",
      "",
      "The parent is providing protection.",
      "",
      "Same event.",
      "",
      "Different perspective.",
      "",
      "Maybe that’s why some prayers go unanswered.",
      "",
      "Maybe that’s why some doors stay closed.",
      "",
      "Maybe that’s why some cravings never seem to work out the way we imagined.",
      "",
      "What feels like divine resistance may actually be divine mercy.",
      "",
      "The beautiful thing about God is that He sees further than we do.",
      "",
      "He sees where certain roads lead.",
      "",
      "He sees where certain habits end.",
      "",
      "He sees where certain desires eventually take us.",
      "",
      "And because He loves us, He sometimes steps into the path of our cravings.",
      "",
      "Not because He enjoys frustrating us.",
      "",
      "But because He enjoys freeing us.",
      "",
      "The older I get, the more I realize that some of God’s greatest blessings arrived disguised as interruptions.",
      "",
      "Some of His greatest mercies arrived disguised as closed doors.",
      "",
      "And some of His greatest acts of love looked an awful lot like frustration in the moment.",
    ],
    remember: "God is not out to get you.\nHe’s out to get you free.",
    prayer: "God, give me wisdom to trust Your interruptions and protection.",
    challenge: [
      "Think about one disappointment from your past that later became a blessing.",
      "",
      "Spend a few moments reflecting on what it taught you.",
      "",
      "Then thank God for a door that didn’t open.",
    ],
    visual: {
      opening: "Fred opens with a closed-door story setup and lands the phrase “God be meddling” with a knowing smile.",
      typography: "The word THWARTS appears, then morphs into PROTECTION, DIRECTION, MERCY.",
      broll: "Closed door, failed deal paperwork, child hand stopped before an outlet, road detour, quiet prayer by a window.",
      onscreen: ["Rejection can be protection.", "God frustrates the craving, not the person.", "He’s out to get you free."],
      tone: "Soulful, humorous, reassuring, reflective.",
      pacing: "Conversational hook, clear theological distinction in the middle, tender gratitude at the end.",
      background: "Warm practical setting; doorways and roads can carry the visual language.",
      clips: ["God be meddling", "Frustrated cravings can be mercy", "Thank God for the door that didn’t open"],
      thumb: "God Be Meddling - Proverbs 10:3",
      cues: "Let “Why, God?” and “Thank God.” contrast emotionally.",
    },
  },
  {
    date: "2026-06-11",
    day: "Thursday",
    dayLine: "Thursday June 11",
    reference: "Proverbs 11:1",
    spokenReference: "Proverbs chapter eleven, verse one",
    translation: "NIV",
    filename: "2026-06-11-proverbs-11-1",
    title: "It’s a Thin Line Between Love and Hate",
    verse:
      "“The Lord detests dishonest scales, but accurate weights find favor with him.”",
    devotional: [
      "It’s a thin line between love and hate.",
      "",
      "At least that’s what the old song says.",
      "",
      "But have you ever wondered what makes that line so thin?",
      "",
      "Maybe it’s because both love and hate are deeply concerned.",
      "",
      "Neither one is indifferent.",
      "",
      "Neither one is neutral.",
      "",
      "Neither one shrugs its shoulders and walks away.",
      "",
      "And that’s what caught my attention when I read today’s proverb.",
      "",
      "Imagine an old marketplace.",
      "",
      "A merchant stands behind his table selling grain.",
      "",
      "He’s friendly.",
      "",
      "Everybody likes him.",
      "",
      "He remembers names. Tells jokes. Smiles often.",
      "",
      "But hidden beneath his scale is a tiny weight.",
      "",
      "Just enough to cheat every customer a little.",
      "",
      "Not enough to start a fight.",
      "",
      "Not enough to get caught.",
      "",
      "Just enough to slowly distort reality.",
      "",
      "One ounce here.",
      "",
      "One ounce there.",
      "",
      "And over time, trust begins to disappear.",
      "",
      "The proverb says God detests dishonest scales.",
      "",
      "That’s strong language.",
      "",
      "But I don’t think the writer is trying to tell us God has emotional mood swings.",
      "",
      "I think he’s trying to communicate something else.",
      "",
      "God is so committed to truth, fairness, and reality that He refuses to give dishonesty any place to stand.",
      "",
      "No room.",
      "",
      "No footing.",
      "",
      "No legitimacy.",
      "",
      "Because dishonest scales don’t merely affect transactions.",
      "",
      "They damage relationships.",
      "",
      "And once trust is broken, reconciliation becomes difficult.",
      "",
      "Most of us don’t own ancient scales.",
      "",
      "But we all have ways of tipping them.",
      "",
      "Telling half the story.",
      "",
      "Making ourselves look better.",
      "",
      "Leaving out important details.",
      "",
      "Presenting a version of reality that benefits us.",
      "",
      "Small distortions.",
      "",
      "Tiny weights.",
      "",
      "But enough to move the scale.",
      "",
      "Here’s the beautiful thing.",
      "",
      "God doesn’t oppose dishonesty because He’s against people.",
      "",
      "He opposes dishonesty because He’s for relationship.",
      "",
      "Truth creates trust.",
      "",
      "Trust creates connection.",
      "",
      "Connection creates unity.",
      "",
      "And unity is where love grows.",
      "",
      "Maybe that’s why dishonest scales receive such strong language.",
      "",
      "Because anything that consistently works against reconciliation will always meet resistance from a God who is constantly working toward it.",
    ],
    remember:
      "God opposes what destroys trust because He desires connection.",
    prayer: "God, remove every dishonest weight and make my scales true.",
    challenge: [
      "Pay attention to your conversations today.",
      "",
      "Notice any temptation to exaggerate, minimize, or distort reality.",
      "",
      "Choose honesty, even in the small things.",
      "",
      "Every truthful word helps recalibrate the scale.",
    ],
    visual: {
      opening: "Fred uses the song-title phrase as the doorway, then reframes strong divine language around love and reconciliation.",
      typography: "Scale graphic with TRUE / DISTORTED and the phrase “tiny weights.”",
      broll: "Marketplace scale, someone editing a text message, half-lit conversation, measuring weights, two people rebuilding trust.",
      onscreen: ["Small distortions move the scale.", "Truth creates trust.", "God desires connection."],
      tone: "Thoughtful, relational, convicting without being harsh.",
      pacing: "Slow and textured through the marketplace image, more direct during the modern application.",
      background: "Neutral desk or studio with a subtle balance/scale prop if available.",
      clips: ["Tiny weights damage trust", "Truth creates connection", "Why God opposes dishonest scales"],
      thumb: "A Thin Line Between Love and Hate - Proverbs 11:1",
      cues: "Keep “No room. No footing. No legitimacy.” crisp and rhythmic.",
    },
  },
  {
    date: "2026-06-12",
    day: "Friday",
    dayLine: "Friday June 12",
    reference: "Proverbs 12:3",
    spokenReference: "Proverbs chapter twelve, verse three",
    translation: "NLT",
    filename: "2026-06-12-proverbs-12-3",
    title: "Deep Roots",
    verse:
      "\"Wickedness never brings stability, but the godly have deep roots.\"",
    devotional: [
      "Everybody wants something that lasts.",
      "",
      "Something stable.",
      "",
      "Something secure.",
      "",
      "Something that can't be taken away.",
      "",
      "We spend a lot of our lives trying to build that kind of security.",
      "",
      "A better job.A bigger savings account.A stronger network.A nicer house.",
      "",
      "None of those things are bad.",
      "",
      "The problem is that every one of them can be lost.",
      "",
      "And that's exactly where today's proverb takes us.",
      "",
      "Notice the contrast.",
      "",
      "Wickedness promises quick results.",
      "",
      "Shortcuts.",
      "",
      "Immediate gains.",
      "",
      "Fast growth.",
      "",
      "But Proverbs says it never produces stability.",
      "",
      "Why?",
      "",
      "Because anything built on distortion eventually has to support a reality it wasn't designed to carry.",
      "",
      "Sooner or later, the foundation gives way.",
      "",
      "But godliness works differently.",
      "",
      "Godliness continually brings us back to center.",
      "",
      "Back to truth.",
      "",
      "Back to reality.",
      "",
      "Back to alignment with God.",
      "",
      "And over time that alignment becomes a root system.",
      "",
      "Deep.Hidden.Strong.",
      "",
      "Think about a musician.",
      "",
      "A truly gifted musician can lose almost everything.",
      "",
      "The guitar can be stolen.",
      "",
      "The studio can close.",
      "",
      "The record deal can disappear.",
      "",
      "The audience can move on.",
      "",
      "But if music is deeply rooted inside them, they haven't lost the source.",
      "",
      "Give them another instrument.",
      "",
      "Give them another room.",
      "",
      "Give them another opportunity.",
      "",
      "And the music will emerge again.",
      "",
      "Because the root is still there.",
      "",
      "The resources changed.",
      "",
      "The source remained.",
      "",
      "That's what this proverb is talking about.",
      "",
      "It's not promising that you'll never lose a house.",
      "",
      "Never lose a job.",
      "",
      "Never lose a relationship.",
      "",
      "It's pointing to something much deeper.",
      "",
      "A person rooted in God's wisdom possesses something that circumstances cannot remove.",
      "",
      "Because their stability doesn't come from what they have.",
      "",
      "It comes from who they are becoming.",
      "",
      "The deepest treasures in life are not possessions.",
      "",
      "They're roots.",
      "",
      "And roots remain even when storms strip away branches.",
    ],
    remember:
      "What is deeply rooted within you can never be taken from you.",
    prayer: "God, deepen my roots in Your wisdom, truth, and love.",
    challenge: [
      "Ask yourself this question:",
      "",
      "What in my life could survive if everything else changed?",
      "",
      "Spend a few moments strengthening that root today.",
    ],
    visual: {
      opening: "Begin with the universal desire for stability, then contrast visible resources with invisible roots.",
      typography: "Words stack downward like roots: TRUTH, REALITY, ALIGNMENT, WISDOM.",
      broll: "Tree roots, musician with a guitar, empty studio, storm moving through trees, hands journaling the challenge question.",
      onscreen: ["Resources changed. Source remained.", "Deep. Hidden. Strong.", "Stability comes from who you are becoming."],
      tone: "Grounded, calm, resilient, hopeful.",
      pacing: "Unhurried and steady; let the musician illustration carry warmth.",
      background: "Natural greens/wood textures or a simple studio with plant/root visual cues.",
      clips: ["What can’t be taken from you?", "Resources vs. roots", "Deep roots survive storms"],
      thumb: "Deep Roots - Proverbs 12:3",
      cues: "For audio, consider separating the compressed source phrases with short pauses: “A better job. A bigger savings account...”",
    },
  },
  {
    date: "2026-06-13",
    day: "Saturday",
    dayLine: "Saturday June 13",
    reference: "Proverbs 13:2",
    spokenReference: "Proverbs chapter thirteen, verse two",
    translation: "NIV",
    filename: "2026-06-13-proverbs-13-2",
    title: "Armageddon Appetite",
    verse:
      "“From the fruit of their lips people enjoy good things, but the unfaithful have an appetite for violence.”",
    devotional: [
      "Back in my college days I discovered a band from Chicago called Resurrection Band.",
      "",
      "Most people knew them as Rez Band.",
      "",
      "They weren’t hip hop.",
      "",
      "They were straight-up rock and roll mixed with Chicago blues.",
      "",
      "And they had this strange little song called “Armageddon Appetite.”",
      "",
      "To this day I still remember it.",
      "",
      "Not because it was their biggest song.",
      "",
      "But because the title stuck with me.",
      "",
      "An appetite for destruction.",
      "",
      "An appetite for chaos.",
      "",
      "An appetite for the end of things.",
      "",
      "And the older I get, the more I realize:",
      "",
      "Everybody’s feeding something.",
      "",
      "This proverb is built around food.",
      "",
      "Fruit.",
      "",
      "Appetite.",
      "",
      "Consumption.",
      "",
      "Taste.",
      "",
      "The writer is asking a simple question:",
      "",
      "What are you feeding on?",
      "",
      "Because eventually what you consume becomes what you crave.",
      "",
      "That’s how appetite works.",
      "",
      "Nobody wakes up one morning craving something they’ve never tasted.",
      "",
      "Appetites are cultivated.",
      "",
      "Developed.",
      "",
      "Acquired.",
      "",
      "What you chew on today shapes what you’ll hunger for tomorrow.",
      "",
      "Think about “food for thought.”",
      "",
      "We use that phrase all the time.",
      "",
      "Because thoughts are a lot like meals.",
      "",
      "Some nourish.",
      "",
      "Some poison.",
      "",
      "Some leave you stronger.",
      "",
      "Others leave you restless.",
      "",
      "You can spend all day feeding on outrage.",
      "",
      "Conflict.",
      "",
      "Fear.",
      "",
      "Division.",
      "",
      "And before long you’ll develop a taste for it.",
      "",
      "An acquired taste.",
      "",
      "An Armageddon Appetite.",
      "",
      "Or you can feed on wisdom.",
      "",
      "Hope.",
      "",
      "Truth.",
      "",
      "Beauty.",
      "",
      "Gratitude.",
      "",
      "And slowly your soul learns to hunger for those things instead.",
      "",
      "The good news is that appetites can change.",
      "",
      "You are not trapped by yesterday’s cravings.",
      "",
      "Every day gives you a new menu.",
      "",
      "A new opportunity to choose what enters your mind and settles in your heart.",
      "",
      "What you repeatedly meditate on eventually becomes what you naturally desire.",
      "",
      "And what you naturally desire eventually shapes your life.",
      "",
      "So choose carefully.",
      "",
      "Because your future is being fed right now.",
    ],
    remember: "What you feed today becomes what you hunger for tomorrow.",
    prayer: "God, give me an appetite for wisdom, truth, and life.",
    challenge: [
      "Pay attention to what you’re mentally consuming today.",
      "",
      "Ask yourself:",
      "",
      "Is this feeding fear, or feeding wisdom?",
      "",
      "Then choose one thing that nourishes your soul and spend time chewing on that instead.",
      "",
      "Bonus Track 🎸",
      "",
      "If you want to revisit the song that inspired the title, here's a place to find \"Armageddon Appetite\" by Rez Band from their 1984 album Hostage. The song appears on the album and is available on Apple Music. (music.apple.com)",
      "",
      "Check it out on YouTube: Armageddon Appetite (Rez Band)",
    ],
    visual: {
      opening: "Open with Fred’s college-days discovery of Rez Band, then let the memorable title become the devotional doorway.",
      typography: "Menu-board layout contrasting OUTRAGE / FEAR / DIVISION with WISDOM / HOPE / GRATITUDE.",
      broll: "Vintage record/CD imagery, Chicago city references, food/menu visuals, phone doom-scroll, person choosing a book/Bible/journal instead.",
      onscreen: ["Everybody’s feeding something.", "What you consume becomes what you crave.", "Your future is being fed right now."],
      tone: "Energetic, nostalgic, warning-with-hope.",
      pacing: "More rhythmic than the rest of the week; let the food/appetite language build momentum.",
      background: "Music-studio accents or subtle rock/blues texture; keep it devotional, not concert-poster heavy.",
      clips: ["Everybody’s feeding something", "Your future is being fed right now", "Appetites can change"],
      thumb: "Armageddon Appetite - Proverbs 13:2",
      cues: "Give “Fruit. Appetite. Consumption. Taste.” a deliberate spoken cadence.",
    },
  },
];

const dirs = {
  master: "episodes/approved/week-one",
  substack: "outputs/reader/substack/week-one",
  site: "outputs/reader/proverbsdaily-org/week-one",
  audio: "outputs/performance/elevenlabs/week-one",
  video: "outputs/video/planning/week-one",
  workflow: "docs/production-workflow",
};

for (const dir of Object.values(dirs)) fs.mkdirSync(dir, { recursive: true });

const mdList = (items) => items.map((item) => `- ${item}`).join("\n");
const join = (lines) => lines.join("\n");
const block = (value, indent = "  ") =>
  String(value)
    .split("\n")
    .map((line) => `${indent}${line}`)
    .join("\n");

const openingBlock = (ep) =>
  [ep.reference, "", ep.verse, "", `Today’s Episode: ${ep.title}`].join("\n");

const spokenVerse = (verse) =>
  verse.replace(/^[“"]/, "").replace(/[”"]$/, "");

const spokenOutro = () =>
  outroFull
    .replace(/❤️|👋🏽/g, "")
    .split("\n")
    .map((line) => line.trim())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");

function sectionedDevotional(ep) {
  return [
    "## Reader Version",
    "",
    `# ${ep.title}`,
    "",
    `**${ep.reference} (${ep.translation})**`,
    "",
    ep.verse,
    "",
    ep.devotional.join("\n"),
  ].join("\n");
}

function performanceVersion(ep) {
  const body = ep.devotional
    .join("\n")
    .replace("A better job.A bigger savings account.A stronger network.A nicer house.", "A better job.\n\nA bigger savings account.\n\nA stronger network.\n\nA nicer house.")
    .replace("Deep.Hidden.Strong.", "Deep.\n\nHidden.\n\nStrong.");

  return [
    ep.reference,
    "",
    spokenVerse(ep.verse),
    "",
    `Today’s Episode: ${ep.title}`,
    "",
    body,
    "",
    ep.remember,
    "",
    ep.prayer,
    "",
    ep.challenge
      .join("\n")
      .replace("Bonus Track 🎸\n\n", "Bonus Track.\n\n"),
    "",
    spokenOutro(),
  ]
    .join("\n")
    .replace(/[🔥🙏🏽🎯🎸]/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd() + "\n";
}

function masterScript(ep) {
  const notes = [
    `Source of truth: ${sourceDoc}`,
    "Generated for Season Two Week One Production Pack v0.2.",
    "Recommended Improvements and Fred Revision Notes are internal only.",
  ];
  if (ep.extractionNote) notes.push(ep.extractionNote);

  return [
    openingBlock(ep),
    "",
    `# ${ep.date} - ${ep.reference} - ${ep.title}`,
    "",
    "## Date",
    ep.date,
    "",
    "## Day",
    ep.day,
    "",
    "## Scripture Reference",
    ep.reference,
    "",
    "## Translation",
    ep.translation,
    "",
    "## Verse Text",
    ep.verse,
    "",
    "## Episode Title",
    `Today’s Episode: ${ep.title}`,
    "",
    sectionedDevotional(ep),
    "",
    "## Performance Version",
    "",
    "```text",
    performanceVersion(ep).trimEnd(),
    "```",
    "",
    "## Remember",
    `🔥 REMEMBER\n${ep.remember}`,
    "",
    "## Prayer",
    `🙏🏽 PRAYER\n${ep.prayer}`,
    "",
    "## Today's Challenge",
    `🎯 TODAY'S CHALLENGE\n${ep.challenge.join("\n")}`,
    "",
    "## Outro",
    outroFull,
    "",
    "## Production Notes",
    mdList(notes),
    "",
    "## Recommended Improvements",
    "- Story opportunities:",
    "- Alternative title ideas:",
    "- Places for Fred texture:",
    "- Potential illustrations:",
    "",
    "## Fred Revision Notes",
    "- No Fred Revision Notes were included in the extracted FINAL document section.",
    "",
    "## Status",
    "APPROVED FOR PRODUCTION REVIEW",
    "",
  ].join("\n");
}

function substackReader(ep) {
  return [
    openingBlock(ep),
    "",
    `**${ep.day}, ${ep.date} | ${ep.translation}**`,
    "",
    ep.devotional.join("\n"),
    "",
    "## 🔥 Remember",
    ep.remember,
    "",
    "## 🙏🏽 Prayer",
    ep.prayer,
    "",
    "## 🎯 Today's Challenge",
    ep.challenge.join("\n"),
    "",
    "## Outro",
    outroFull,
    "",
  ].join("\n");
}

function siteReader(ep) {
  return [
    `scriptureReference: ${ep.reference}`,
    `translation: ${ep.translation}`,
    "verseText: |-",
    block(ep.verse),
    `title: ${ep.title}`,
    "devotional: |-",
    block(ep.devotional.join("\n")),
    "remember: |-",
    block(ep.remember),
    "prayer: |-",
    block(ep.prayer),
    "challenge: |-",
    block(ep.challenge.join("\n")),
    "",
  ].join("\n");
}

function videoNotes(ep) {
  const notes = [
    `Source: ${sourceDoc}`,
    "Recommended Improvements in the source were blank placeholders.",
    "Fred Revision Notes in the source were blank for this episode.",
  ];
  if (ep.extractionNote) notes.push(ep.extractionNote);

  return [
    `# Video Planning Notes - ${ep.date} - ${ep.title}`,
    "",
    `## Episode`,
    `- Day: ${ep.day}`,
    `- Scripture: ${ep.reference} (${ep.translation})`,
    `- Status: APPROVED FOR PRODUCTION REVIEW`,
    "",
    "## Talking-Head Opening",
    ep.visual.opening,
    "",
    "## Scripture Typography Moment",
    ep.visual.typography,
    "",
    "## Visual / B-Roll Ideas",
    ep.visual.broll,
    "",
    "## On-Screen Text Moments",
    mdList(ep.visual.onscreen),
    "",
    "## Emotional Tone",
    ep.visual.tone,
    "",
    "## Suggested Pacing",
    ep.visual.pacing,
    "",
    "## Suggested Background Visuals",
    ep.visual.background,
    "",
    "## Short-Form Clip Ideas",
    mdList(ep.visual.clips),
    "",
    "## Thumbnail/Title Idea",
    ep.visual.thumb,
    "",
    "## Optional Emotional Cues for ElevenLabs or Voice Performance",
    ep.visual.cues,
    "",
    "## Closing/CTA Reference",
    outroFull,
    "",
    "## Internal Planning Inputs",
    mdList(notes),
    "",
  ].join("\n");
}

function workflowDoc() {
  return [
    "# Season Two Week One Production Pack Strategy",
    "",
    "## Source of Truth",
    `The FINAL docx is the production source of truth: ${sourceDoc}. Older rough draft files are not production sources and should only be consulted for reference when absolutely necessary.`,
    "",
    "## Pack Structure",
    "- Approved master scripts live in `episodes/approved/week-one/` and are for production review.",
    "- Substack files live in `outputs/reader/substack/week-one/` and are reader-facing.",
    "- ProverbsDaily.org files live in `outputs/reader/proverbsdaily-org/week-one/` and are structured for app/web publishing.",
    "- ElevenLabs files live in `outputs/performance/elevenlabs/week-one/` and are audio-safe plain spoken text.",
    "- Video planning files live in `outputs/video/planning/week-one/` and are creative production notes.",
    "",
    "## Internal Notes",
    "Recommended Improvements and Fred Revision Notes are internal only. They may guide video planning or production decisions, but they should not appear in reader-facing, app/web, or ElevenLabs files.",
    "",
    "## v0.2 Formatting Note",
    "The FINAL document opening sequence is authoritative: scripture reference, verse text, then `Today’s Episode: [title]`. Codex must not smooth, rephrase, or add generated opening language such as `Today’s Proverbs Daily is called...`, `Proverbs chapter seven, verse one says...`, or similar introductions.",
    "",
    "Outro bumper rules are platform-specific: Substack keeps the full reader-facing bumper with emojis; ElevenLabs keeps the full spoken bumper with emojis removed only; approved master scripts keep the bumper as part of the approved master; video planning files reference the bumper as the closing/CTA sequence.",
    "",
    "ProverbsDaily.org excludes the outro bumper because the web app already has its own About the Author card. Those files should end after Today's Challenge.",
    "",
    "## Editorial Authority",
    "Fred remains the final editorial authority for script changes, performance choices, publishing decisions, and any unresolved extraction questions.",
    "",
  ].join("\n");
}

for (const ep of episodes) {
  fs.writeFileSync(path.join(dirs.master, `${ep.filename}.md`), masterScript(ep));
  fs.writeFileSync(path.join(dirs.substack, `${ep.filename}.md`), substackReader(ep));
  fs.writeFileSync(path.join(dirs.site, `${ep.filename}.md`), siteReader(ep));
  fs.writeFileSync(path.join(dirs.audio, `${ep.filename}.txt`), performanceVersion(ep));
  fs.writeFileSync(path.join(dirs.video, `${ep.filename}.md`), videoNotes(ep));
}

fs.writeFileSync(
  path.join(dirs.workflow, "week-one-production-pack-strategy.md"),
  workflowDoc(),
);

console.log(`Created ${episodes.length} approved master scripts`);
console.log(`Created ${episodes.length} Substack files`);
console.log(`Created ${episodes.length} ProverbsDaily.org files`);
console.log(`Created ${episodes.length} ElevenLabs files`);
console.log(`Created ${episodes.length} video planning files`);
console.log("Episodes needing Fred review: none");
