const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const GENERATED_AT = "2026-06-14T12:00:00.000-05:00";

const OUTRO_PLACEHOLDER = "[OUTRO PLACEHOLDER - add approved Proverbs Daily reader/listener support bumper after Fred approval.]";

const episodes = [
  {
    date: "2026-06-14",
    day: "Sunday",
    dayOfMonth: 14,
    chapter: 14,
    candidateVerses: ["Proverbs 14:15", "Proverbs 14:26", "Proverbs 14:29", "Proverbs 14:30", "Proverbs 14:31"],
    coveragePercent: 22.86,
    coverageNotes: "Chapter 14 has 8 covered verses and 27 remaining unused verses. No local verse-theme metadata exists yet for chapter 14.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 14:30",
    translationSuggestion: "KJV for rough-draft text; Fred may swap to ESV, NIV, or NLT in revision.",
    verseText: "A sound heart is the life of the flesh: but envy the rottenness of the bones.",
    score: 88,
    scoreReasoning: "Strong because the verse gives a concrete body image, connects to the Stayin' Alive/heart seed, and creates a practical emotional-health episode without becoming generic.",
    ties: ["Proverbs 14:29"],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 14 theme metadata.",
    idea: {
      ideaId: "idea-006",
      ideaTitle: "Stayin' Alive",
      cleanSummary: "A seed connecting CPR, rhythm, heart, music, and the idea that the right inner rhythm helps preserve life.",
      category: "Science And Life",
      persona: "Musician",
      metaSubject: "emotional health"
    },
    titles: ["Quiet Bones", "The Rhythm Under Your Skin", "When Envy Gets In The Body", "A Sound Heart", "The Inner Pulse"],
    workingTitle: "Quiet Bones",
    hooks: [
      "CPR teaches that rhythm can help preserve life.",
      "Some emotions do not stay in your head; they move into your body.",
      "Envy can look spiritual or ambitious until it starts eating your peace."
    ],
    illustrations: ["CPR class rhythm", "phone battery draining in the background", "a quiet heart changing the atmosphere of a room"],
    remember: "A quiet heart can heal what envy keeps inflaming.",
    prayer: "God, tune my heart toward life and peace.",
    challenge: "Name one envy trigger today. Bless that person, then release the comparison.",
    strongerTitle: "The Inner Pulse",
    strongerHook: "Start with the CPR rhythm, then move to the unseen rhythm inside the heart.",
    draft: [
      "Proverbs 14:30",
      "",
      "A sound heart is the life of the flesh: but envy the rottenness of the bones.",
      "",
      "Today's Episode: Quiet Bones",
      "",
      "# 2026-06-14 - Proverbs 14:30 - Quiet Bones",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "I took a CPR class once, and one of the things that stuck with me was the rhythm.",
      "",
      "You do not just press randomly.",
      "",
      "There is a tempo.",
      "",
      "There is a beat.",
      "",
      "There is a way your hands learn to move so a body has a better chance to keep living.",
      "",
      "And I remember thinking: that is wild.",
      "",
      "A song can become a lifesaving metronome.",
      "",
      "A rhythm can help preserve a life.",
      "",
      "Then Proverbs walks in and says, do not only pay attention to the rhythm in your chest. Pay attention to the rhythm in your heart.",
      "",
      "Proverbs 14:30 says:",
      "",
      "\"A sound heart is the life of the flesh: but envy the rottenness of the bones.\"",
      "",
      "That is not just poetry.",
      "",
      "That is diagnosis.",
      "",
      "The writer is telling us that what happens inside us does not stay inside us.",
      "",
      "A sound heart gives life.",
      "",
      "A settled heart.",
      "",
      "A heart that is not always competing, comparing, scanning the room, counting somebody else's blessing like God misplaced yours.",
      "",
      "That kind of heart has a healing rhythm.",
      "",
      "But envy?",
      "",
      "Envy does not just make you want what somebody else has.",
      "",
      "Envy starts making you suspicious of the life God gave you.",
      "",
      "It turns another person's joy into your private injury.",
      "",
      "It takes a testimony and makes it feel like an insult.",
      "",
      "And Proverbs says that kind of thing can get in the bones.",
      "",
      "Not literally like an X-ray report, but deeply. Structurally. Down where strength is supposed to live.",
      "",
      "## Revisit Verse Text",
      "",
      "\"A sound heart is the life of the flesh: but envy the rottenness of the bones.\"",
      "",
      "## Scripture Breakdown",
      "",
      "The contrast is not between success and failure.",
      "",
      "It is between soundness and envy.",
      "",
      "A sound heart is aligned. It can celebrate without shrinking. It can want more without despising what it already has. It can see somebody else's open door without accusing God of closing yours.",
      "",
      "That is wisdom.",
      "",
      "Not pretending you never desire anything.",
      "",
      "Not acting like comparison never knocks.",
      "",
      "Wisdom is learning not to let envy set the tempo.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about your phone with too many apps running in the background.",
      "",
      "The screen may look normal, but the battery is draining.",
      "",
      "Envy works like that.",
      "",
      "You can smile, function, post, work, and serve while comparison quietly drains your joy in the background.",
      "",
      "A sound heart closes the apps.",
      "",
      "It says, I do not have to compete with what God is doing in somebody else.",
      "",
      "I can participate in what God is forming in me.",
      "",
      "## Encouraging Turn",
      "",
      "The good news is that the heart can be tuned again.",
      "",
      "You are not stuck with envy as your rhythm.",
      "",
      "Gratitude can interrupt it.",
      "",
      "Blessing others can weaken it.",
      "",
      "Contentment can teach your soul to breathe again.",
      "",
      "God is not trying to shame you for feeling comparison.",
      "",
      "He is inviting you into a healthier pulse.",
      "",
      "## Remember Point",
      "",
      "A quiet heart can heal what envy keeps inflaming.",
      "",
      "## 10-Word Prayer",
      "",
      "God, tune my heart toward life and peace.",
      "",
      "## Today's Challenge",
      "",
      "Name one envy trigger today.",
      "",
      "A person.",
      "",
      "A platform.",
      "",
      "A conversation.",
      "",
      "A number.",
      "",
      "Then bless that person on purpose and release the comparison before it gets into your bones.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred could add the specific CPR class detail and whether the Stayin' Alive reference should stay in the final.",
      "- Consider tightening the phone-battery illustration if the CPR image is strong enough by itself.",
      "- Confirm final translation before production.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Needs Fred texture around rhythm, music, and comparison."
    ]
  },
  {
    date: "2026-06-15",
    day: "Monday",
    dayOfMonth: 15,
    chapter: 15,
    candidateVerses: ["Proverbs 15:1", "Proverbs 15:2", "Proverbs 15:3", "Proverbs 15:17", "Proverbs 15:23"],
    coveragePercent: 27.27,
    coverageNotes: "Chapter 15 has 9 covered verses and 24 remaining unused verses. No local verse-theme metadata exists yet for chapter 15.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 15:1",
    translationSuggestion: "KJV for rough-draft text; Fred may prefer NIV or ESV for final readability.",
    verseText: "A soft answer turneth away wrath: but grievous words stir up anger.",
    score: 92,
    scoreReasoning: "Very strong because the verse is familiar, highly practical, and fits the Make The World A Better Place seed through small speech choices that change the atmosphere.",
    ties: [],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 15 theme metadata.",
    idea: {
      ideaId: "idea-011",
      ideaTitle: "Make The World A Better Place",
      cleanSummary: "A seed about small forms of goodness, love, and delight changing the atmosphere people carry into the world.",
      category: "Everyday Wisdom",
      persona: "Citizen",
      metaSubject: "speech and atmosphere"
    },
    titles: ["Turn Down The Heat", "The Volume Of Peace", "Soft Answers, Strong Rooms", "Change The Weather", "Lower The Flame"],
    workingTitle: "Turn Down The Heat",
    hooks: [
      "Some people know how to walk into a room and change the weather.",
      "A soft answer is not weak; it is temperature control.",
      "Not every fire needs more volume."
    ],
    illustrations: ["thermostat in a tense house", "coffee changing the morning atmosphere", "a text reply drafted twice before sending"],
    remember: "A soft answer is strength with the temperature turned down.",
    prayer: "God, make my words strong enough to be gentle.",
    challenge: "Before one tense reply today, pause and lower the temperature.",
    strongerTitle: "The Volume Of Peace",
    strongerHook: "Use a thermostat image: the room may be hot, but wisdom decides not to add heat.",
    draft: [
      "Proverbs 15:1",
      "",
      "A soft answer turneth away wrath: but grievous words stir up anger.",
      "",
      "Today's Episode: Turn Down The Heat",
      "",
      "# 2026-06-15 - Proverbs 15:1 - Turn Down The Heat",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "Some people can walk into a room and change the weather.",
      "",
      "Not because they are loud.",
      "",
      "Not because they take over.",
      "",
      "Not because everybody is afraid of them.",
      "",
      "They just carry a kind of peace that lowers the temperature.",
      "",
      "And some people do the opposite.",
      "",
      "They walk in and suddenly the room gets hotter.",
      "",
      "Words get sharper.",
      "",
      "Faces tighten.",
      "",
      "Everybody starts choosing their sentences carefully because one wrong syllable might set the whole thing off.",
      "",
      "Proverbs 15:1 says:",
      "",
      "\"A soft answer turneth away wrath: but grievous words stir up anger.\"",
      "",
      "That verse is not saying soft words are weak words.",
      "",
      "It is saying soft words can be strong enough to redirect wrath.",
      "",
      "That is a different kind of power.",
      "",
      "Anybody can escalate.",
      "",
      "Anybody can match energy.",
      "",
      "Anybody can say, well, if you come at me like that, I am coming right back.",
      "",
      "But wisdom asks a better question:",
      "",
      "What does this moment need from me?",
      "",
      "Does it need more heat?",
      "",
      "Or does it need someone with enough inner strength to turn the temperature down?",
      "",
      "## Revisit Verse Text",
      "",
      "\"A soft answer turneth away wrath: but grievous words stir up anger.\"",
      "",
      "## Scripture Breakdown",
      "",
      "The proverb gives us two directions speech can move.",
      "",
      "One kind of answer turns wrath away.",
      "",
      "Another kind stirs anger up.",
      "",
      "So words are not neutral.",
      "",
      "They are either a thermostat or a match.",
      "",
      "A soft answer does not mean dishonest flattery. It does not mean avoiding truth. It does not mean letting people mistreat you.",
      "",
      "It means wisdom has learned how to tell the truth without pouring gasoline on the room.",
      "",
      "That is not cowardice.",
      "",
      "That is formation.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about a text message you type when you are mad.",
      "",
      "You know the first draft.",
      "",
      "The one with punctuation that needs pastoral counseling.",
      "",
      "The one where every sentence has a little smoke coming off it.",
      "",
      "Sometimes wisdom is not deleting the truth.",
      "",
      "Sometimes wisdom is waiting long enough for the truth to stop swinging.",
      "",
      "You can still say what needs to be said.",
      "",
      "You can still set a boundary.",
      "",
      "You can still be clear.",
      "",
      "But you do not have to hand your anger the microphone.",
      "",
      "## Encouraging Turn",
      "",
      "This is how small goodness travels.",
      "",
      "A gentle reply can save a morning.",
      "",
      "A measured response can protect a friendship.",
      "",
      "A calm word can keep a child from carrying shame.",
      "",
      "A soft answer can make the world better, not in a dramatic way, but in a daily way.",
      "",
      "One conversation at a time.",
      "",
      "One room at a time.",
      "",
      "One lowered flame at a time.",
      "",
      "## Remember Point",
      "",
      "A soft answer is strength with the temperature turned down.",
      "",
      "## 10-Word Prayer",
      "",
      "God, make my words strong enough to be gentle.",
      "",
      "## Today's Challenge",
      "",
      "Before one tense reply today, pause.",
      "",
      "Ask: am I about to be a thermostat or a match?",
      "",
      "Then answer in a way that lowers the heat without hiding the truth.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred could add a family, ministry, or online comment-section moment.",
      "- Decide whether the coffee/morning atmosphere seed should be added or saved for another chapter.",
      "- Consider alternate title: The Volume Of Peace.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Good practical shape; needs Fred's lived voice and final translation."
    ]
  },
  {
    date: "2026-06-16",
    day: "Tuesday",
    dayOfMonth: 16,
    chapter: 16,
    candidateVerses: ["Proverbs 16:1", "Proverbs 16:2", "Proverbs 16:5", "Proverbs 16:9", "Proverbs 16:20"],
    coveragePercent: 27.27,
    coverageNotes: "Chapter 16 has 9 covered verses and 24 remaining unused verses. No local verse-theme metadata exists yet for chapter 16.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 16:9",
    translationSuggestion: "KJV for rough-draft text; ESV or NIV may fit final spoken cadence.",
    verseText: "A man's heart deviseth his way: but the LORD directeth his steps.",
    score: 90,
    scoreReasoning: "Strong because it combines planning, technology/GPS imagery, and Fred's participation-over-control theological instinct.",
    ties: ["Proverbs 16:1"],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 16 theme metadata.",
    idea: {
      ideaId: "idea-001",
      ideaTitle: "Grace In The Machine",
      cleanSummary: "A seed about finding grace inside systems, technology, automation, or mechanical processes.",
      category: "Technology",
      persona: "Citizen",
      metaSubject: "guidance"
    },
    titles: ["The Route Recalculates", "Grace In The Detour", "Plans With A Pulse", "When God Handles The Steps", "The Map Is Not The Master"],
    workingTitle: "The Route Recalculates",
    hooks: [
      "GPS has made us bold and helpless at the same time.",
      "Planning is human; direction is holy.",
      "Sometimes grace sounds like rerouting."
    ],
    illustrations: ["GPS rerouting", "calendar plans changing", "app development mistakes becoming a better rebuild"],
    remember: "Plan faithfully, but leave room for God to direct the steps.",
    prayer: "God, guide my steps beyond my best plans.",
    challenge: "Hold one plan open today and ask God to direct the next step.",
    strongerTitle: "Grace In The Detour",
    strongerHook: "Open with GPS rerouting after a missed turn and treat the recalculation as mercy, not failure.",
    draft: [
      "Proverbs 16:9",
      "",
      "A man's heart deviseth his way: but the LORD directeth his steps.",
      "",
      "Today's Episode: The Route Recalculates",
      "",
      "# 2026-06-16 - Proverbs 16:9 - The Route Recalculates",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "GPS has made us both bold and helpless.",
      "",
      "Bold, because we will drive into a city we do not know with full confidence.",
      "",
      "Helpless, because if the signal drops, suddenly we are pioneers.",
      "",
      "And one of the funniest phrases in modern life is that calm little voice that says:",
      "",
      "Rerouting.",
      "",
      "You missed the turn.",
      "",
      "You ignored the exit.",
      "",
      "You thought you knew a better way.",
      "",
      "And the machine does not shame you.",
      "",
      "It just recalculates.",
      "",
      "That may be one of the smallest pictures of grace we carry around every day.",
      "",
      "Proverbs 16:9 says:",
      "",
      "\"A man's heart deviseth his way: but the LORD directeth his steps.\"",
      "",
      "That verse does not insult planning.",
      "",
      "It assumes planning.",
      "",
      "The heart devises the way.",
      "",
      "We dream.",
      "",
      "We calendar.",
      "",
      "We budget.",
      "",
      "We build.",
      "",
      "We make decisions with the light we have.",
      "",
      "But the Lord directs the steps.",
      "",
      "Not because our planning is worthless.",
      "",
      "Because our planning is limited.",
      "",
      "## Revisit Verse Text",
      "",
      "\"A man's heart deviseth his way: but the LORD directeth his steps.\"",
      "",
      "## Scripture Breakdown",
      "",
      "There is a beautiful tension here.",
      "",
      "Wisdom does not say, do nothing and call it faith.",
      "",
      "And wisdom does not say, control everything and call it responsibility.",
      "",
      "It gives us participation without pretending we are sovereign.",
      "",
      "You plan the way.",
      "",
      "God directs the steps.",
      "",
      "That means your plan can be sincere and still need correction.",
      "",
      "Your dream can be real and still need timing.",
      "",
      "Your goal can be good and still need a detour.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about rebuilding something after you have already made a bunch of mistakes.",
      "",
      "An app.",
      "",
      "A song.",
      "",
      "A relationship.",
      "",
      "A ministry system.",
      "",
      "You thought the mistake was wasted time.",
      "",
      "Then later you realized it taught you what not to do.",
      "",
      "The wrong turns became part of the map.",
      "",
      "The missed takes helped you find the right take.",
      "",
      "That does not mean every mistake was God's preference.",
      "",
      "But it does mean God can direct steps even through roads you did not mean to take.",
      "",
      "## Encouraging Turn",
      "",
      "So do not despise the reroute.",
      "",
      "Sometimes grace sounds like interruption.",
      "",
      "Sometimes mercy looks like a closed road.",
      "",
      "Sometimes God is not blocking your life.",
      "",
      "He is directing your steps.",
      "",
      "Plan faithfully.",
      "",
      "Work honestly.",
      "",
      "But keep your hands open enough for God to guide what your map could not see.",
      "",
      "## Remember Point",
      "",
      "Plan faithfully, but leave room for God to direct the steps.",
      "",
      "## 10-Word Prayer",
      "",
      "God, guide my steps beyond my best plans.",
      "",
      "## Today's Challenge",
      "",
      "Choose one plan you are holding tightly.",
      "",
      "Pray over it today.",
      "",
      "Then ask God for the next faithful step, not the whole map.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred could connect this to rebuilding the Proverbs Daily app after earlier mistakes.",
      "- Consider whether Grace In The Machine should be explicit or just implied through GPS/rerouting.",
      "- Confirm final translation and whether 'man's heart' should be updated in final copy.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Strong draft candidate; needs Fred's tech/app story texture."
    ]
  },
  {
    date: "2026-06-17",
    day: "Wednesday",
    dayOfMonth: 17,
    chapter: 17,
    candidateVerses: ["Proverbs 17:1", "Proverbs 17:6", "Proverbs 17:9", "Proverbs 17:10", "Proverbs 17:14"],
    coveragePercent: 32.14,
    coverageNotes: "Chapter 17 has 9 covered verses and 19 remaining unused verses. No local verse-theme metadata exists yet for chapter 17.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 17:1",
    translationSuggestion: "KJV for rough-draft text; NLT may make this verse especially speakable after Fred review.",
    verseText: "Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife.",
    score: 86,
    scoreReasoning: "Strong because the verse gives a table image, household emotional wisdom, and a clean practical application around peace over performance.",
    ties: ["Proverbs 17:9"],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 17 theme metadata.",
    idea: {
      ideaId: "idea-011",
      ideaTitle: "Make The World A Better Place",
      cleanSummary: "A seed about small forms of goodness, love, and delight changing the atmosphere people carry into the world.",
      category: "Everyday Wisdom",
      persona: "Husband",
      metaSubject: "home atmosphere"
    },
    titles: ["Quiet Tastes Better", "A Better Kind Of Table", "Peace Is Part Of The Meal", "When The House Is Too Loud", "Dry Bread, Quiet Room"],
    workingTitle: "Quiet Tastes Better",
    hooks: [
      "A meal can be expensive and still taste like tension.",
      "Peace is not a side dish; sometimes it is the whole meal.",
      "You can have a full table and an empty atmosphere."
    ],
    illustrations: ["family table tension", "quiet coffee morning", "a good meal ruined by unresolved conflict"],
    remember: "Peace can make simple bread taste like blessing.",
    prayer: "God, make my presence part of the peace.",
    challenge: "Do one small thing today that makes your home easier to breathe in.",
    strongerTitle: "Peace Is Part Of The Meal",
    strongerHook: "Open with an expensive meal that nobody enjoys because tension is sitting at the table.",
    draft: [
      "Proverbs 17:1",
      "",
      "Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife.",
      "",
      "Today's Episode: Quiet Tastes Better",
      "",
      "# 2026-06-17 - Proverbs 17:1 - Quiet Tastes Better",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "A meal can be expensive and still taste like tension.",
      "",
      "You can have the good plates out.",
      "",
      "The table set.",
      "",
      "The food seasoned right.",
      "",
      "The candles doing their little atmospheric ministry.",
      "",
      "And still, everybody at the table knows something is off.",
      "",
      "Because peace is not a side dish.",
      "",
      "Sometimes peace is the meal.",
      "",
      "Proverbs 17:1 says:",
      "",
      "\"Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife.\"",
      "",
      "That is a strong image.",
      "",
      "Dry bread with quietness is better than a house full of feast food with strife.",
      "",
      "Not because food does not matter.",
      "",
      "Not because provision does not matter.",
      "",
      "But because abundance without peace can still feel poor.",
      "",
      "You can have more on the table and less in the soul.",
      "",
      "You can have a full pantry and an exhausted household.",
      "",
      "You can have a beautiful room that nobody feels safe in.",
      "",
      "## Revisit Verse Text",
      "",
      "\"Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife.\"",
      "",
      "## Scripture Breakdown",
      "",
      "The word picture is simple.",
      "",
      "On one side: a dry morsel.",
      "",
      "Plain bread.",
      "",
      "Nothing impressive.",
      "",
      "But quietness is there.",
      "",
      "On the other side: a house full of sacrifices.",
      "",
      "That sounds like abundance, celebration, religious activity, maybe even public honor.",
      "",
      "But strife is there too.",
      "",
      "And Proverbs says wisdom would rather have less with peace than more with constant conflict.",
      "",
      "That is not small thinking.",
      "",
      "That is soul-level accounting.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about a morning cup of coffee.",
      "",
      "For somebody who loves coffee, that cup can change the whole day.",
      "",
      "Not because coffee solves everything.",
      "",
      "But because small goodness can change the atmosphere you carry into the world.",
      "",
      "A peaceful home can do the same thing.",
      "",
      "A gentle greeting.",
      "",
      "An apology before the day gets busy.",
      "",
      "A decision not to bring yesterday's argument into today's kitchen.",
      "",
      "A little quietness can travel.",
      "",
      "It can go with somebody to work, to school, to traffic, to ministry, to the next room.",
      "",
      "## Encouraging Turn",
      "",
      "This proverb is not asking you to pretend every house is peaceful.",
      "",
      "It is inviting you to value peace enough to practice it.",
      "",
      "Sometimes the wisest thing you can bring to the table is not another opinion.",
      "",
      "It is a softer tone.",
      "",
      "A repaired relationship.",
      "",
      "A refusal to keep score.",
      "",
      "A willingness to let love be louder than the need to win.",
      "",
      "## Remember Point",
      "",
      "Peace can make simple bread taste like blessing.",
      "",
      "## 10-Word Prayer",
      "",
      "God, make my presence part of the peace.",
      "",
      "## Today's Challenge",
      "",
      "Do one small thing today that makes your home easier to breathe in.",
      "",
      "Clear a mess.",
      "",
      "Speak gently.",
      "",
      "Apologize first.",
      "",
      "Or simply choose not to stir the strife.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred may want to add a marriage/family table story.",
      "- Decide whether the coffee line belongs here or should be saved for a full Make The World A Better Place episode.",
      "- A modern translation may make 'dry morsel' clearer for listeners.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Warm household episode; needs Fred's exact intimacy boundary for family/marriage references."
    ]
  },
  {
    date: "2026-06-18",
    day: "Thursday",
    dayOfMonth: 18,
    chapter: 18,
    candidateVerses: ["Proverbs 18:1", "Proverbs 18:10", "Proverbs 18:15", "Proverbs 18:20", "Proverbs 18:21"],
    coveragePercent: 37.5,
    coverageNotes: "Chapter 18 has 9 covered verses and 15 remaining unused verses. No local verse-theme metadata exists yet for chapter 18.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 18:21",
    translationSuggestion: "KJV for rough-draft text; NIV or NLT may be stronger for final speech rhythm.",
    verseText: "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.",
    score: 94,
    scoreReasoning: "Very strong because it is vivid, practical, and directly matches the Cheep Speech Ain't Free seed without repeating the Week One appetite title.",
    ties: [],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 18 theme metadata.",
    idea: {
      ideaId: "idea-010",
      ideaTitle: "Cheep Speech Ain't Free",
      cleanSummary: "A seed about speech that seems cheap but carries real cost and consequence.",
      category: "Speech And Consequence",
      persona: "Citizen",
      metaSubject: "speech"
    },
    titles: ["Words With Teeth", "That Mouth Has A Receipt", "Cheap Talk Gets Expensive", "The Fruit Of Your Mouth", "Speech Is Never Free"],
    workingTitle: "Words With Teeth",
    hooks: [
      "Words feel weightless until the bill arrives.",
      "Speech is never as cheap as it feels in the moment.",
      "Your mouth is planting fruit somebody will eventually eat."
    ],
    illustrations: ["receipts after impulse spending", "comment thread escalation", "fruit from seeds planted earlier"],
    remember: "Words feel free until someone has to eat the fruit.",
    prayer: "God, put life in my mouth today.",
    challenge: "Speak one life-giving sentence today where criticism would be easier.",
    strongerTitle: "That Mouth Has A Receipt",
    strongerHook: "Open with cheap talk that feels free until the relational receipt prints.",
    draft: [
      "Proverbs 18:21",
      "",
      "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.",
      "",
      "Today's Episode: Words With Teeth",
      "",
      "# 2026-06-18 - Proverbs 18:21 - Words With Teeth",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "Words feel weightless until the bill arrives.",
      "",
      "You can say it quick.",
      "",
      "Post it quick.",
      "",
      "Text it quick.",
      "",
      "Drop the comment, make the joke, throw the little verbal elbow, and in the moment it feels cheap.",
      "",
      "Free, even.",
      "",
      "But then the receipt prints.",
      "",
      "A relationship gets colder.",
      "",
      "A child remembers a sentence you forgot.",
      "",
      "A friend starts pulling back.",
      "",
      "A room changes after your words walk through it.",
      "",
      "That is why Proverbs 18:21 says:",
      "",
      "\"Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.\"",
      "",
      "That mouth has a receipt.",
      "",
      "Speech is not just sound.",
      "",
      "It is seed.",
      "",
      "It is fruit.",
      "",
      "It is power moving through breath.",
      "",
      "And Proverbs refuses to let us pretend our words are smaller than they are.",
      "",
      "## Revisit Verse Text",
      "",
      "\"Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.\"",
      "",
      "## Scripture Breakdown",
      "",
      "Notice the verse does not say death and life are only in big speeches.",
      "",
      "It says they are in the power of the tongue.",
      "",
      "Ordinary speech.",
      "",
      "Kitchen speech.",
      "",
      "Car speech.",
      "",
      "Church hallway speech.",
      "",
      "Group chat speech.",
      "",
      "The words we release casually may still carry consequences seriously.",
      "",
      "And then the verse uses eating language.",
      "",
      "Those who love it will eat its fruit.",
      "",
      "In other words, your speech grows a harvest.",
      "",
      "Eventually somebody is going to live off what your mouth has been planting.",
      "",
      "Maybe them.",
      "",
      "Maybe you.",
      "",
      "Probably both.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about a comment thread online.",
      "",
      "It starts with one sentence.",
      "",
      "Then somebody adds a sharper sentence.",
      "",
      "Then somebody adds sarcasm.",
      "",
      "Then somebody screenshots it.",
      "",
      "Before long, nobody is really seeking truth anymore.",
      "",
      "Everybody is just eating the fruit of words that were planted in anger.",
      "",
      "But the same thing works in the other direction.",
      "",
      "A word of courage can stay with somebody for years.",
      "",
      "A blessing can interrupt shame.",
      "",
      "A calm answer can save the room.",
      "",
      "An honest apology can plant life where death was starting to grow.",
      "",
      "## Encouraging Turn",
      "",
      "This is not condemnation.",
      "",
      "This is invitation.",
      "",
      "If death and life are in the tongue, then God has placed life-giving possibility closer than we think.",
      "",
      "You do not need a platform to plant life.",
      "",
      "You need a mouth surrendered to wisdom.",
      "",
      "You need one sentence that refuses to cooperate with death.",
      "",
      "One sentence can bless.",
      "",
      "One sentence can heal.",
      "",
      "One sentence can tell the truth with love.",
      "",
      "## Remember Point",
      "",
      "Words feel free until someone has to eat the fruit.",
      "",
      "## 10-Word Prayer",
      "",
      "God, put life in my mouth today.",
      "",
      "## Today's Challenge",
      "",
      "Speak one life-giving sentence today where criticism would be easier.",
      "",
      "Encourage somebody.",
      "",
      "Bless somebody.",
      "",
      "Apologize to somebody.",
      "",
      "Plant fruit you would not mind eating later.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred can decide whether to use 'Cheep Speech Ain't Free' as the final title or keep it as a seed.",
      "- Consider adding a personal hip-hop lyric-writing angle around words carrying weight.",
      "- Source video linked in the idea seed should be reviewed before any direct reference.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Strongest raw draft candidate; likely title decision needed."
    ]
  },
  {
    date: "2026-06-19",
    day: "Friday",
    dayOfMonth: 19,
    chapter: 19,
    candidateVerses: ["Proverbs 19:1", "Proverbs 19:3", "Proverbs 19:20", "Proverbs 19:21", "Proverbs 19:23"],
    coveragePercent: 34.48,
    coverageNotes: "Chapter 19 has 10 covered verses and 19 remaining unused verses. No local verse-theme metadata exists yet for chapter 19.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 19:21",
    translationSuggestion: "KJV for rough-draft text; ESV or NIV may be best for final clarity.",
    verseText: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.",
    score: 87,
    scoreReasoning: "Strong because it pairs well with creative process, failed attempts, and plans submitted to God's steadier counsel.",
    ties: ["Proverbs 19:20"],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text and missing chapter 19 theme metadata.",
    idea: {
      ideaId: "idea-009",
      ideaTitle: "Risk Take - Miss Take - This Take",
      cleanSummary: "A seed about learning through failed attempts until mistakes become the map toward the right take.",
      category: "Creative Process",
      persona: "Musician",
      metaSubject: "discernment"
    },
    titles: ["Plans With Open Hands", "Many Takes, One Counsel", "The Take That Stands", "When Your Plan Meets Counsel", "Hold The Blueprint Lightly"],
    workingTitle: "Plans With Open Hands",
    hooks: [
      "Creative people know how many takes it can take to find the take.",
      "Your heart can hold a hundred plans, but only God's counsel can carry the weight.",
      "Some plans are sketches; counsel is architecture."
    ],
    illustrations: ["studio takes", "app rebuild mistakes", "a blueprint revised after seeing the foundation"],
    remember: "Your plans can change without God's counsel losing its footing.",
    prayer: "God, steady my plans inside Your counsel.",
    challenge: "Write one plan in pencil today and submit it to God's counsel.",
    strongerTitle: "Many Takes, One Counsel",
    strongerHook: "Use the studio language of multiple takes until the right take appears.",
    draft: [
      "Proverbs 19:21",
      "",
      "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.",
      "",
      "Today's Episode: Plans With Open Hands",
      "",
      "# 2026-06-19 - Proverbs 19:21 - Plans With Open Hands",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "Creative people know how many takes it can take to find the take.",
      "",
      "You try one version.",
      "",
      "Miss.",
      "",
      "Try another.",
      "",
      "Miss.",
      "",
      "Change the tempo.",
      "",
      "Move the hook.",
      "",
      "Rewrite the line.",
      "",
      "Start over.",
      "",
      "And if you are paying attention, the misses are not always wasted.",
      "",
      "Sometimes the mistake becomes the map.",
      "",
      "Sometimes the failed take teaches you where the right take is hiding.",
      "",
      "Proverbs 19:21 says:",
      "",
      "\"There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.\"",
      "",
      "That verse feels like it understands the human mind.",
      "",
      "Many devices.",
      "",
      "Many plans.",
      "",
      "Many schemes.",
      "",
      "Many tabs open in the soul.",
      "",
      "We can imagine five futures before breakfast.",
      "",
      "We can rehearse conversations that have not happened.",
      "",
      "We can build whole castles out of what if.",
      "",
      "And Proverbs does not deny that.",
      "",
      "It simply says there is something stronger than the pile of plans inside us.",
      "",
      "The counsel of the Lord stands.",
      "",
      "## Revisit Verse Text",
      "",
      "\"There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.\"",
      "",
      "## Scripture Breakdown",
      "",
      "The contrast is between our many and God's steady.",
      "",
      "We have many plans.",
      "",
      "God has counsel that stands.",
      "",
      "That does not mean planning is wrong.",
      "",
      "It means plans need a place to bow.",
      "",
      "A plan becomes dangerous when it cannot be corrected.",
      "",
      "A dream becomes heavy when it has to become God.",
      "",
      "A strategy becomes an idol when we cannot release it, revise it, or submit it.",
      "",
      "Wisdom lets the heart make plans, but it lets the Lord have final counsel.",
      "",
      "## Practical Living Illustration",
      "",
      "Think about a blueprint.",
      "",
      "On paper, everything looks clean.",
      "",
      "Then you get to the actual ground.",
      "",
      "The soil is different.",
      "",
      "The measurements need adjusting.",
      "",
      "Something underground changes the plan above ground.",
      "",
      "The wise builder does not scream at the dirt.",
      "",
      "The wise builder listens to reality and adjusts.",
      "",
      "Sometimes God's counsel does that in us.",
      "",
      "It meets our plan with truth.",
      "",
      "It meets our ambition with timing.",
      "",
      "It meets our urgency with patience.",
      "",
      "It meets our fear with a firmer foundation.",
      "",
      "## Encouraging Turn",
      "",
      "You do not have to be embarrassed that your plans changed.",
      "",
      "Growth changes plans.",
      "",
      "Wisdom changes plans.",
      "",
      "Healing changes plans.",
      "",
      "God's counsel is not threatened by your revisions.",
      "",
      "The mercy is that something stands even when your first draft does not.",
      "",
      "Your plan may be pencil.",
      "",
      "God's counsel is foundation.",
      "",
      "## Remember Point",
      "",
      "Your plans can change without God's counsel losing its footing.",
      "",
      "## 10-Word Prayer",
      "",
      "God, steady my plans inside Your counsel.",
      "",
      "## Today's Challenge",
      "",
      "Write one plan in pencil today.",
      "",
      "Literally or mentally.",
      "",
      "Then pray: Lord, correct what needs correcting and establish what is Yours.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred could add a studio recording or Proverbs Daily app-building mistake story.",
      "- Consider tying 'Risk Take - Miss Take - This Take' more explicitly into the title.",
      "- Confirm whether this overlaps too much with June 16 guidance language.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Good creative-process seed; watch overlap with Proverbs 16:9."
    ]
  },
  {
    date: "2026-06-20",
    day: "Saturday",
    dayOfMonth: 20,
    chapter: 20,
    candidateVerses: ["Proverbs 20:4", "Proverbs 20:9", "Proverbs 20:18", "Proverbs 20:24", "Proverbs 20:27"],
    coveragePercent: 20,
    coverageNotes: "Chapter 20 has 6 covered verses and 24 remaining unused verses. No local verse-theme metadata exists yet for chapter 20.",
    priorUsageNotes: "Selected verse is listed as unused in the local coverage query.",
    duplicateWarnings: [],
    recommendedVerse: "Proverbs 20:24",
    translationSuggestion: "KJV for rough-draft text; NLT may be clearest for final spoken delivery.",
    verseText: "Man's goings are of the LORD; how can a man then understand his own way?",
    score: 84,
    scoreReasoning: "Strong but a little more abstract. It creates a good hidden-guidance episode and matches the See It And Forget It seed, but it needs Fred texture to avoid sounding too similar to Proverbs 16:9.",
    ties: ["Proverbs 20:18"],
    reviewStatus: "NEEDS_FRED_REVIEW - KJV text, missing chapter 20 theme metadata, and thematic overlap with June 16.",
    idea: {
      ideaId: "idea-005",
      ideaTitle: "See It And Forget It",
      cleanSummary: "A seed about hidden growth, unseen strength, and formation that happens away from public attention.",
      category: "Hidden Growth",
      persona: "Father",
      metaSubject: "hidden guidance"
    },
    titles: ["Walking Without The Whole Map", "The Map Is Not The Master", "When The Way Is Hidden", "Guided Before You Get It", "Steps You Understand Later"],
    workingTitle: "Walking Without The Whole Map",
    hooks: [
      "Some paths only make sense after you have walked them.",
      "You can be guided before you understand.",
      "Not every hidden thing is absent; some things are forming underground."
    ],
    illustrations: ["roots growing in the dark", "looking back at a confusing season", "a parent guiding a child through a crowd"],
    remember: "You can be guided before you understand where you are going.",
    prayer: "God, guide me when understanding comes later.",
    challenge: "Take the next wise step today without demanding the full explanation.",
    strongerTitle: "Guided Before You Get It",
    strongerHook: "Open with looking back at a confusing season that only made sense later.",
    draft: [
      "Proverbs 20:24",
      "",
      "Man's goings are of the LORD; how can a man then understand his own way?",
      "",
      "Today's Episode: Walking Without The Whole Map",
      "",
      "# 2026-06-20 - Proverbs 20:24 - Walking Without The Whole Map",
      "",
      "## Opening Hook / Devotional Body",
      "",
      "Some paths only make sense after you have walked them.",
      "",
      "While you are in it, it just feels confusing.",
      "",
      "A delay.",
      "",
      "A detour.",
      "",
      "A season that seems too quiet.",
      "",
      "A door that will not open.",
      "",
      "A skill you are learning but do not know why.",
      "",
      "Then later, you look back and realize something was being formed in the dark.",
      "",
      "The roots were growing before the fruit had anything to show.",
      "",
      "Proverbs 20:24 says:",
      "",
      "\"Man's goings are of the LORD; how can a man then understand his own way?\"",
      "",
      "That is a humbling verse.",
      "",
      "It does not say we never understand anything.",
      "",
      "It says there is a limit to what we can understand while we are still walking.",
      "",
      "You can be in the middle of God's guidance and still not have the full explanation.",
      "",
      "That can be frustrating.",
      "",
      "But it can also be freeing.",
      "",
      "Because understanding is not the same thing as being guided.",
      "",
      "## Revisit Verse Text",
      "",
      "\"Man's goings are of the LORD; how can a man then understand his own way?\"",
      "",
      "## Scripture Breakdown",
      "",
      "The verse puts two truths beside each other.",
      "",
      "Our steps are not random to God.",
      "",
      "And our understanding is not complete.",
      "",
      "Both are true.",
      "",
      "God can be directing a life that still feels unclear to the person living it.",
      "",
      "That means confusion is not proof of abandonment.",
      "",
      "Delay is not proof of waste.",
      "",
      "Hidden growth is not proof that nothing is happening.",
      "",
      "Sometimes you have to see it and forget it.",
      "",
      "See the seed go into the ground.",
      "",
      "Then trust the dark work you cannot monitor every day.",
      "",
      "## Practical Living Illustration",
      "",
      "A parent walking a child through a crowded place understands this.",
      "",
      "The child may not know why you turned left.",
      "",
      "Why you slowed down.",
      "",
      "Why you said, hold my hand right now.",
      "",
      "The child does not see the whole crowd.",
      "",
      "The parent sees more.",
      "",
      "The child may not understand the way, but the child can still be guided through it.",
      "",
      "That is not punishment.",
      "",
      "That is care.",
      "",
      "## Encouraging Turn",
      "",
      "Maybe today you are asking God for the whole map.",
      "",
      "And maybe God is offering the next wise step.",
      "",
      "Do not despise that.",
      "",
      "A next step is not a small thing when God is in it.",
      "",
      "The path may become clearer behind you than it is in front of you.",
      "",
      "But the Lord is not confused because you are.",
      "",
      "Your understanding may arrive later.",
      "",
      "His guidance can be present now.",
      "",
      "## Remember Point",
      "",
      "You can be guided before you understand where you are going.",
      "",
      "## 10-Word Prayer",
      "",
      "God, guide me when understanding comes later.",
      "",
      "## Today's Challenge",
      "",
      "Take the next wise step today without demanding the full explanation.",
      "",
      "Make the call.",
      "",
      "Tell the truth.",
      "",
      "Do the work.",
      "",
      "Rest if rest is the step.",
      "",
      "Trust that guidance can be real before clarity is complete.",
      "",
      "## Outro Placeholder",
      "",
      OUTRO_PLACEHOLDER,
      "",
      "## Recommended Improvements",
      "",
      "- Fred should decide whether this overlaps too closely with June 16's route/recalculate draft.",
      "- The See It And Forget It seed's source video should be reviewed before any direct reference.",
      "- Consider a stronger Saturday hook with a personal hidden-growth story.",
      "",
      "## Fred Revision Notes",
      "",
      "- DRAFT FOR FRED REVIEW. Weakest draft only because of overlap risk; still has a useful hidden-guidance frame."
    ]
  }
];

function writeJson(relativePath, value) {
  const filePath = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeText(relativePath, value) {
  const filePath = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, value.endsWith("\n") ? value : `${value}\n`, "utf8");
}

function planRows() {
  return episodes.map((episode) => ({
    date: episode.date,
    day: episode.day,
    dayOfMonth: episode.dayOfMonth,
    chapter: episode.chapter,
    candidateUnusedVerses: episode.candidateVerses,
    coverageNotes: episode.coverageNotes,
    priorUsageNotes: episode.priorUsageNotes,
    duplicateWarnings: episode.duplicateWarnings,
    status: "Planning Draft"
  }));
}

function recommendationRows() {
  return episodes.map((episode) => ({
    ...planRows().find((row) => row.date === episode.date),
    recommendedVerse: episode.recommendedVerse,
    recommendation: {
      score: episode.score,
      confidence: episode.score >= 90 ? "High" : "Medium",
      reasoning: episode.scoreReasoning
    },
    ties: episode.ties,
    reviewStatus: episode.reviewStatus
  }));
}

function ideaRows() {
  return episodes.map((episode) => ({
    ...recommendationRows().find((row) => row.date === episode.date),
    suggestedDirections: [
      {
        ...episode.idea,
        matchedCandidateVerses: [episode.recommendedVerse],
        matchConfidence: "Manual Producer Pass",
        matchReason: "Matched by chapter, idea reservoir possibilities, visible verse concept, and Season Two draft needs."
      }
    ]
  }));
}

function titleRows() {
  return episodes.map((episode) => ({
    ...ideaRows().find((row) => row.date === episode.date),
    titleSuggestions: episode.titles,
    recommendedWorkingTitle: episode.workingTitle,
    duplicateTitleWarning: "No exact Week One title repeat. Season One title-history check should be confirmed before approval.",
    callAudible: false
  }));
}

function briefRows() {
  return episodes.map((episode) => ({
    date: episode.date,
    day: episode.day,
    scriptureReference: episode.recommendedVerse,
    translationSuggestion: episode.translationSuggestion,
    verseText: episode.verseText,
    workingTitle: episode.workingTitle,
    suggestedDirection: episode.idea.cleanSummary,
    persona: episode.idea.persona,
    metaSubject: episode.idea.metaSubject,
    hookPossibilities: episode.hooks,
    practicalIllustrationPossibilities: episode.illustrations,
    rememberDirection: episode.remember,
    prayerDirection: episode.prayer,
    challengeDirection: episode.challenge,
    reviewStatus: episode.reviewStatus
  }));
}

function packetMarkdown() {
  const lines = [
    "# Proverbs Daily Season Two Week Two Draft Packet",
    "",
    "Date range: 2026-06-14 through 2026-06-20",
    "",
    "Status: Sunday producer-session rough drafts. Not approved. Not production copy.",
    "",
    "Translation note: KJV verse text is used here as public-domain rough-draft text where needed. Fred should choose the final production translation during review.",
    ""
  ];

  episodes.forEach((episode) => {
    lines.push("---", "", ...episode.draft, "");
  });

  return lines.join("\n");
}

function producerReviewMarkdown() {
  const lines = [
    "# Season Two Week Two Producer Session Review",
    "",
    "Date range: 2026-06-14 through 2026-06-20",
    "",
    "Purpose: Fred review surface for the Week Two rough draft scripts. These are not final production files.",
    ""
  ];

  episodes.forEach((episode) => {
    lines.push(
      `## ${episode.date} - ${episode.recommendedVerse} - ${episode.workingTitle}`,
      "",
      "Rating: Green / Yellow / Red",
      "",
      "Final approval status: PENDING FRED REVIEW",
      "",
      "### What works",
      "",
      `- Scripture direction: ${episode.scoreReasoning}`,
      `- Dominant image: ${episode.illustrations[0]}.`,
      `- Remember line: ${episode.remember}`,
      "",
      "### What needs Fred texture",
      "",
      `- ${episode.reviewStatus}`,
      "- Add lived story details, theological precision, and final spoken cadence.",
      "- Confirm final translation before any production output.",
      "",
      "### Possible stronger title",
      "",
      `- ${episode.strongerTitle}`,
      "",
      "### Possible stronger hook",
      "",
      `- ${episode.strongerHook}`,
      "",
      "### Questions for Fred",
      "",
      "- Does this verse feel like the right center of gravity for the day?",
      "- Is the working title Fred-voice or just useful scaffolding?",
      "- What personal story, ministry moment, music reference, or family texture belongs here?",
      "- Should this stay a standalone draft, combine with another day, or be rejected?",
      ""
    );
  });

  return lines.join("\n");
}

function main() {
  writeJson("data/episode-manifest/week-two/weeklyPlan.json", {
    week: "Season Two Week Two",
    dateRange: { start: "2026-06-14", end: "2026-06-20" },
    rows: planRows(),
    lastUpdated: GENERATED_AT
  });

  writeJson("data/episode-manifest/week-two/weeklyPlanWithVerseRecommendations.json", {
    week: "Season Two Week Two",
    rows: recommendationRows(),
    lastUpdated: GENERATED_AT
  });

  writeJson("data/episode-manifest/week-two/weeklyPlanWithIdeas.json", {
    week: "Season Two Week Two",
    rows: ideaRows(),
    lastUpdated: GENERATED_AT
  });

  writeJson("data/episode-manifest/week-two/weeklyPlanWithTitles.json", {
    week: "Season Two Week Two",
    rows: titleRows(),
    lastUpdated: GENERATED_AT
  });

  writeJson("data/episode-manifest/week-two/weeklyEpisodeBriefs.json", {
    week: "Season Two Week Two",
    briefs: briefRows(),
    lastUpdated: GENERATED_AT
  });

  episodes.forEach((episode) => {
    writeText(`episodes/drafts/week-two/${episode.date}.md`, episode.draft.join("\n"));
  });

  writeText("outputs/reader/google-docs/week-two/weekly-draft-packet.md", packetMarkdown());
  writeText("docs/producer-sessions/week-two/week-two-producer-session-review.md", producerReviewMarkdown());

  console.log("Created Season Two Week Two draft pack v0.1");
  episodes.forEach((episode) => {
    console.log(`${episode.date}: ${episode.recommendedVerse} - ${episode.workingTitle}`);
  });
}

if (require.main === module) {
  main();
}
