const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const manifestPath = path.join(ROOT, "data/production/week-two/productionManifest.week25.json");
const prepPath = path.join(ROOT, "outputs/audio/week-two/review/audio-batch-prep-week25.md");

function run() {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const lines = [
    "# Week Two ElevenLabs Audio Batch Prep",
    "",
    "No audio has been generated by this script. It prepares the batch list for a future ElevenLabs API integration.",
    "",
    "Source: `outputs/approved/week-two/weekly-approved-performance-script-week-25.md`",
    "",
    "## Episodes",
    "",
  ];

  for (const episode of manifest.episodes) {
    lines.push(
      `- ${episode.date} | ${episode.scriptureReference} | ${episode.title}`,
      `  - rawAudio: ${episode.audioRawPath}`,
      `  - reviewNotes: ${episode.audioReviewPath}`,
      `  - elevenLabsStatus: ${episode.elevenLabsStatus}`,
      ""
    );
  }

  fs.mkdirSync(path.dirname(prepPath), { recursive: true });
  fs.writeFileSync(prepPath, `${lines.join("\n").trim()}\n`, "utf8");
  console.log(`Created ${path.relative(ROOT, prepPath)}`);
}

if (require.main === module) {
  run();
}
